# Generated by Django 3.1.7 on 2021-09-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeeksModel',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='textfiled',
            new_name='textfield',
        ),
    ]
